env:
  browser: true
  es6: true
  node: true

extends:
  - 'airbnb-base',
  - 'eslint:recomended'

parser: babel-eslint

rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always

  no-console: 0
  